---
# Complete playbook which configures JIRA to use PostgreSQL database
# and HAProxy frontend
- hosts: issues
  become: true
  pre_tasks:
    - name: install packages required for testing
      yum: name={{ item }} state=present
      with_items:
        - libselinux-python
        - net-tools
    - name: disable selinux during testing
      selinux: policy=targeted state=permissive

  roles:
    - role: galaxyprojectdotorg.postgresql
    - role: williamyeh.oracle-java
    - role: uoi-io.haproxy
      tags: ['haproxy']
    - role: dgptamayo.jira

  tasks:
    - name: install packages required for managing postgresql
      yum: name=python-psycopg2 state=present

    - name: creating db user '{{ jira_db_user }}'
      postgresql_user:
        name: "{{ jira_db_user }}"
        password: "{{ jira_db_pass }}"
        encrypted: yes
      become_user: postgres

    - name: creating db '{{ jira_db }}'
      postgresql_db:
        name: "{{ jira_db }}"
        owner: "{{ jira_db_user }}"
      become_user: postgres

  vars:
    # NOTE: Use pre-downloaded JIRA package in files/
    jira_download_from_remote: true
    java_version: 8
    java_subversion: 101
    # NOTE: For speedy testing, download jdk-8u92-linux-x64.rpm to files/
    java_download_from_oracle: true
    jira_db: "jira"
    jira_db_user: "jirauser"
    jira_db_pass: "jirapass"
    jira_manage_service: true
    postgresql_pg_hba_local_ipv4: ''
    postgresql_pg_hba_local_ipv6: ''
    postgresql_pg_hba_conf:
      - 'host    all             all             127.0.0.1/32            md5'
      - 'host    all             all             ::1/128                 md5'
    haproxy_firewalld: false
    haproxy_selinux: false
    haproxy_stats_uri: /haproxy?stats
    haproxy_stats_user: "admin"
    haproxy_stats_password: "admin"
    haproxy_listen:
      - jira:
          mode: http
          description: JIRA Software
          balance: roundrobin
          binds:
            - "*:80"
          timeouts:
            - server 2m
            - client 2m
          servers:
          - jira 127.0.0.1:8080 check
